#!/bin/sh

# Example of how to build with browserify
# You will need to `npm install uglify-js --save-dev` first

echo "-> Building production version"
NODE_ENV=production webpack

# echo "-> Uglify"
# uglifyjs public/bundle.js -cm -v false -o public/jsapp.min.js
# 
# echo "-> Gzip"
# gzip -k -f -9 public/jsapp.min.js
# 
# echo "-> Copy the files to the Rails app"
# mv public/jsapp.min.js* ../app/assets/javascripts/skydrive/.

echo "-> Copying bundle.js to Rails asset pipeline"
cp public/bundle.js* ../app/assets/javascripts/skydrive/.
